### ISSUE TITLE
Gerenciar Usuários

### ISSUE THREAD

**Issue by rafaelspa** [ifspcodelab/event-platform-backend#9]
Eu, como administrador, quero gerenciar usuários para visualizar os registros.

**Critérios de aceitação**

- [x] A página "Gerenciar Usuário" deve ter apenas uma busca por nome no layout inicial.
- [x] A página deve fazer puxar do banco os dados de nome, e-mail, cpf, perfis, email_confirmado, data_de_cadastro, minicurrículo, lattes, linkedin e celular.
- [x] Os dados buscados devem ser paginadas de 20 em 20.
- [x] A página deve carregar os dados nos devidos campos da tabela.
- [x] A página deve ser acessível apenas a quem tiver o perfil "Admin".
- [x] Deve ter um log com os dados de quem fez a busca.

**Comment by diegocelestino** [comment]
História finalizada em detrimento dessa outra ---> https://github.com/ifspcodelab/event-platform-backend/issues/73
